# Site
title:              BRF Doktor Lindh
bio:                'Bostadsrättsföreningen Doktor Lindh på Sädra Guldheden i Göteborg'
description:        "Bostadsrättsföreningen Doktor Lindh på Sädra Guldheden i Göteborg"
locale:             sv_SE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
teaser: 400x250.png # 400x250 px default teaser image used in image archive grid

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

collections:
  for_medlemmar:
    permalink: /:collection/:name
    output: true
  om_foreningen:
    permalink: /:collection/:name
    output: true
  pagaende_projekt:
    permalink: /:collection/:name
    output: true
  kontakt:
    permalink: /:collection/:name
    output: true
  
# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   default

# Social
#analytics-id:       "default"
#twitter:            default
#facebook:           default
#instagram:          default
#github:             default

# personal
location:           Brf Dr. Lindh<br>Dr. Lindhs gata 3<br>413 25 Göteborg
email:              drlindh@gmail.com

# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 2
  permalink: '/notiser/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

include:
  - _redirects
 
# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true
