#backend:
#  name: git-gateway
backend:
  name: github
  repo: drlindh/www # Path to your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go

# publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Notiser" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Liten bild (rek storlek: 400x250)", name: "teaser", widget: "image", default: "/images/400x250.png"}
      - {label: "Stor bild (valfritt)", name: "feature", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
    # PAGES
  - name: "page"
    label: "Huvudsidor"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h2", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Stor bild (valfritt, rek storlek: 1024x256)", name: "feature", widget: "image", required: false}
      - {label: "Collection", name: "collection", widget: "hidden"}
      - {label: "pagination", name: "pagination", widget: "hidden"}
    # Medlemsinfo
  - name: "for_medlemmar"
    label: "För medlemmar"
    folder: "_for_medlemmar"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Liten bild (rek storlek: 400x250)", name: "teaser", widget: "image", default: "/images/400x250.png"}
      - {label: "Stor bild (valfritt, rek storlek: 1024x256)", name: "feature", widget: "image", required: false}
  - name: "om_foreningen"
    label: "Om föreningen"
    folder: "_om_foreningen"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Liten bild (rek storlek: 400x250)", name: "teaser", widget: "image", default: "/images/400x250.png"}
      - {label: "Stor bild (valfritt, rek storlek: 1024x256)", name: "feature", widget: "image", required: false}
  - name: "kontakt"
    label: "Kontaktinformation"
    folder: "_kontakt"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Liten bild (rek storlek: 400x250)", name: "teaser", widget: "image", default: "/images/400x250.png"}
      - {label: "Stor bild (valfritt, rek storlek: 1024x256)", name: "feature", widget: "image", required: false}
  - name: "pagaende_projekt"
    label: "Pågående projekt"
    folder: "_pagaende_projekt"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Liten bild (rek storlek: 400x250)", name: "teaser", widget: "image", default: "/images/400x250.png"}
      - {label: "Stor bild (valfritt, rek storlek: 1024x256)", name: "feature", widget: "image", required: false}
